# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: zeal_sales12
  pool: 5
  username: root
  password: this.admin
  host: localhost

# # test:
#   adapter: mysql2
#   encoding: utf
#   reconnect: false
#   database: crm_test
#   pool: 5
#   username: root
#   password: this.admin
#   host: localhost
#   port: 3306
 
# production:
#   adapter: mysql2
#   encoding: utf8
#   reconnect: false
#   database: crm_sales_production
#   username: root
#   password: this.admin
#   pool: 5
#   host: localhost
#   port: 3306